-- Create Database and Schema Structure
-- Mirrors the AWS Lakehouse architecture in Snowflake

USE ROLE SYSADMIN;

-- Create database for lakehouse data
CREATE DATABASE IF NOT EXISTS LAKEHOUSE
  COMMENT = 'Database for AWS Lakehouse integration';

-- Create schemas for each layer
CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.BRONZE
  COMMENT = 'Bronze layer - Raw data from S3';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.SILVER
  COMMENT = 'Silver layer - Cleaned data from S3';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.GOLD
  COMMENT = 'Gold layer - Aggregated data from S3';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.ANALYTICS
  COMMENT = 'Analytics layer - Snowflake-specific transformations';

-- Create file formats for different data types
CREATE OR REPLACE FILE FORMAT LAKEHOUSE.PUBLIC.PARQUET_FORMAT
  TYPE = PARQUET
  COMPRESSION = SNAPPY;

CREATE OR REPLACE FILE FORMAT LAKEHOUSE.PUBLIC.CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE
  COMPRESSION = GZIP;

CREATE OR REPLACE FILE FORMAT LAKEHOUSE.PUBLIC.JSON_FORMAT
  TYPE = JSON
  COMPRESSION = AUTO;

-- Create stages pointing to S3 buckets
CREATE OR REPLACE STAGE LAKEHOUSE.SILVER.silver_stage
  STORAGE_INTEGRATION = aws_lakehouse_integration
  URL = 's3://your-silver-bucket/cleaned/'
  FILE_FORMAT = LAKEHOUSE.PUBLIC.PARQUET_FORMAT;

CREATE OR REPLACE STAGE LAKEHOUSE.GOLD.gold_stage
  STORAGE_INTEGRATION = aws_lakehouse_integration
  URL = 's3://your-gold-bucket/aggregated/'
  FILE_FORMAT = LAKEHOUSE.PUBLIC.PARQUET_FORMAT;

-- Grant permissions
GRANT USAGE ON DATABASE LAKEHOUSE TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LAKEHOUSE TO ROLE DATA_ENGINEER;
GRANT ALL ON ALL STAGES IN DATABASE LAKEHOUSE TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL FILE FORMATS IN DATABASE LAKEHOUSE TO ROLE DATA_ENGINEER;

-- Verify setup
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE LAKEHOUSE;
SHOW STAGES IN DATABASE LAKEHOUSE;
