AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Data Engineering Lakehouse Architecture - Infrastructure Setup'

Parameters:
  ProjectName:
    Type: String
    Default: 'lakehouse'
    Description: 'Project name for resource naming'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - staging
      - prod
    Description: 'Environment name'

Resources:
  # S3 Bucket for Lakehouse Storage
  LakehouseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Glue Database for Bronze Layer
  BronzeDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_bronze_db'
        Description: 'Bronze layer database for raw data'

  # Glue Database for Silver Layer
  SilverDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_silver_db'
        Description: 'Silver layer database for cleansed data'

  # Glue Database for Gold Layer
  GoldDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_gold_db'
        Description: 'Gold layer database for analytical data'

  # IAM Role for Glue Jobs
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-glue-job-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt LakehouseBucket.Arn
                  - !Sub '${LakehouseBucket.Arn}/*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/glue/*'

  # IAM Role for Glue Crawlers
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-glue-crawler-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt LakehouseBucket.Arn
                  - !Sub '${LakehouseBucket.Arn}/*'

  # Athena Workgroup
  AthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub '${ProjectName}-workgroup'
      Description: 'Athena workgroup for lakehouse analytics'
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub 's3://${LakehouseBucket}/athena-results/'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true

  # SNS Topic for Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alerts'
      DisplayName: 'Lakehouse Pipeline Alerts'
      Subscription:
        - Endpoint: 'your-email@example.com'
          Protocol: email

  # CloudWatch Log Group
  GlueJobLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/glue/jobs/${ProjectName}'
      RetentionInDays: 30

Outputs:
  LakehouseBucketName:
    Description: 'S3 Bucket for Lakehouse Storage'
    Value: !Ref LakehouseBucket
    Export:
      Name: !Sub '${ProjectName}-bucket-name'

  GlueJobRoleArn:
    Description: 'IAM Role ARN for Glue Jobs'
    Value: !GetAtt GlueJobRole.Arn
    Export:
      Name: !Sub '${ProjectName}-glue-job-role-arn'

  GlueCrawlerRoleArn:
    Description: 'IAM Role ARN for Glue Crawlers'
    Value: !GetAtt GlueCrawlerRole.Arn
    Export:
      Name: !Sub '${ProjectName}-glue-crawler-role-arn'

  AthenaWorkgroupName:
    Description: 'Athena Workgroup Name'
    Value: !Ref AthenaWorkgroup
    Export:
      Name: !Sub '${ProjectName}-athena-workgroup'

  AlertTopicArn:
    Description: 'SNS Topic ARN for Alerts'
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${ProjectName}-alert-topic-arn'
